---
  - name: Install packages.
    apt:
      pkg="{{ item }}"
      state=present
    with_items: "{{ apt_install }}"
    when: apt_install


#  - name: Installing NodeJS
#    become: yes
#    apt:
#      name: nodejs
#      state: installed
#    tags:
#      - nodejs-install
#
#  - name: Installing NodeJS legacy
#    become: yes
#    apt:
#      name: nodejs-legacy
#      state: installed
#    tags:
#      - nodejs-legacy-install
#
#
#  - name: Install packages
#    apt:
#      pkg: "{{ item }}"
#      state: present
#      update_cache: yes
#    with_items:
#      - git
#      - emacs
#      - firefox
#      - tmux
#      - htop
#
#  - name: Download phpstorm
#    get_url:
#      url: https://download.jetbrains.com/webide/PhpStorm-2016.3.2.tar.gz
#      dest: /tmp/phpstorm.tar.gz
#
#  - name: Unpack phpstorm
#    unarchive:
#      src: /tmp/phpstorm.tar.gz
#      dest: /opt/
#      owner: "{{ user }}"
#      creates: /opt/PhpStorm-163.10504.2
#    register: unpack
#
#  - name: Fix the PHPStorm permissions folder
#    file:
#      path: /opt/PhpStorm-163.10504.2
#      owner: "{{ user }}"
#      recurse: yes
#    when: unpack.changed
#
#  - name: Create phpstorm .desktop file
#    copy:
#      src: ../files/jetbrains-phpstorm.desktop
#      dest: /usr/share/applications/jetbrains-phpstorm.desktop
#      owner: root
#      group: root
#      mode: "u=rw,g=r,o=r"