---
  - include: update.yml
  - include: apt_repositories/dependencies.yml
  - include: apt_repositories/repositories.yml
  - include: upgrade.yml
  - include: install.yml
  - include: remove.yml
  - include: debian/debian.yml
  - include: users/setup_user.yml
  #- include: reboot.yml
  # gsettings set org.gnome.desktop.interface font-name 'Calibri 12'
  - name: install base packages
    apt: pkg={{item}} state=present update_cache=yes cache_valid_time=604800
    with_items:
      - sysstat
      - htop
      - git
      - subversion
      - mercurial
      - python-samba
      - vim
      - virtualbox
      - vagrant
      - indicator-multiload
      - chromium-browser
      - sublime-text
      - rdesktop
      - openvpn
      - python-dev
      - r-base
      - r-recommended
      - tilemill
      - classicmenu-indicator
      - gimp
      - inkscape
      - ruby-dev
      - sqlite
      - pgadmin3
      - postgresql
      - libpq-dev
      - python-psycopg2
      - imagemagick
      - marble
      - mapserver-bin
      - python-mapscript
      - python-matplotlib
      - liblas-bin
      - gdal-bin
      - python-gdal
      - grass
      - libspatialite-dev
      - spatialite-gui
      - spatialite-bin
      - libzmq-dev
      - qgis
      - pandoc
      - texlive-latex-base
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-fonts-recommended
      - unity-tweak-tool
      - xclip
      - sqliteman
      - filezilla
      - gummi
      - texmaker
      - keepassx
      - wireshark
      - cifs-utils
#  - include: base.yml
#    become: false
#
#  - include: apt.yml
#    when: ansible_os_family = 'Debian' and ansible_distribution == 'Ubuntu' and ansible_pkg_mgr == 'apt'
#
#  - include: yum.yml
#    when: ansible_os_family = 'RedHat' and ansible_distribution == 'CentOS' and ansible_pkg_mgr == 'yum'
#    become: false
#
#  - include: homebrew.yml
#    when: ansible_os_family = 'Darwin'
#    become: false


#- name: Include variables suitable to our OS Family
#  include_vars: "{{ item }}"
#  with_first_found:
#    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
#- "{{ ansible_os_family }}.yml"