---
  - name: PHP | Add php-7.1 ondrej PPA
    apt_repository: repo={{ php__ppa }}
                    state=present
                    update_cache=yes
    become: yes

  - name: Update apt
    become: yes
    apt: update_cache=yes

  - name: Install PHP | install php packages
    become: yes
    apt: pkg={{ item }} state=latest
    with_items: "{{ php__packages }}"
    when: php__packages is defined

  - name: Install PHP dev packages
    become: yes
    apt: pkg={{ item }} state=latest
    when: env__vagrant == true
    with_items: "{{ php__dev_packages }}"
    when: php__dev_packages is defined

  - name: Copy project based PHP configuration
    become: yes
    template: src=project.ini.j2 dest=/etc/php/7.1/mods-available/project.ini backup=yes

  - name: Configure PHP CLI
    become: yes
    file: src=/etc/php/7.1/mods-available/project.ini dest=/etc/php/7.1/cli/conf.d/project.ini state=link

  - name: Configure PHP CGI
    become: yes
    file: src=/etc/php/7.1/mods-available/project.ini dest=/etc/php/7.1/fpm/conf.d/project.ini state=link
    notify:
        - restart php7-fpm

  - name: Set post_max_size
    become: yes
    lineinfile: dest=/etc/php/7.1/fpm/php.ini
                regexp='post_max_size(\s)?='
                line='post_max_size = {{ php_post_max_size }}'
    notify: restart php7-fpm

  - name: Set upload_max_filesize
    become: yes
    lineinfile: dest=/etc/php/7.1/fpm/php.ini
                regexp='upload_max_filesize(\s)?='
                line='upload_max_filesize = {{ php_upload_max_filesize }}'
                create=yes
    notify: restart php7-fpm

  - name: Set memory_limit
    become: yes
    lineinfile: dest=/etc/php/7.1/fpm/php.ini
                regexp='memory_limit(\s)?='
                line='memory_limit = {{ php_memory_limit }}'
    notify: restart php7-fpm

  - include: pecl.yml
