---
# file: ansible.role.openvpn/tasks/main.yml

  - name: Install OpenVPN
    apt: name='openvpn' state=present force=yes
    when: ansible_os_family == "Debian" and ansible_distribution == "Ubuntu"  and ansible_architecture == "x86_64" and ansible_pkg_mgr == "apt"

  - name: Install OpenVPN
    apt: name='network-manager-openvpn' state=present force=yes
    when: ansible_os_family == "Debian" and ansible_distribution == "Ubuntu"  and ansible_architecture == "x86_64" and ansible_pkg_mgr == "apt"