---
  - name: Step 1 Download and install Heroku CLI
    shell: >
      sudo apt-get install software-properties-common  # debian only
    when: ansible_pkg_mgr == 'apt'
    register: HerokuCLI-Step1

  - name: Step 2 Download and install Heroku CLI
    shell: >
      sudo add-apt-repository "deb https://cli-assets.heroku.com/branches/stable/apt ./"
    when: ansible_pkg_mgr == 'apt'

  - name: Step 3 Download and install Heroku CLI
    shell: >
      curl -L https://cli-assets.heroku.com/apt/release.key | sudo apt-key add -
    when: ansible_pkg_mgr == 'apt'

  - name: Install Heroku
    apt:
      pkg: "{{ item }}"
      state: present
    with_items:
      - heroku
    when: ansible_pkg_mgr == 'apt'