---
  - name: Download Debian Packages
    become: yes
    get_url:
      url: "{{ item.url }}"
      dest: "/tmp/{{ item.deb }}"
      mode: 0644
    with_items: "{{ apt_debian_packages }}"
    when: apt_debian_packages

  - name: install Debian Packages Dependies
    shell: >
      sudo apt-get install -f

  - name: install deb packages manually
    action: shell dpkg-query -f '${Package}\n' -W {{item.name}} || dpkg -i /tmp/{{item.deb}}
    register: deb
    changed_when: deb.stdout != item.name
    with_items: "{{ apt_debian_packages }}"
    when: apt_debian_packages