---

  - name: Copy configuration files
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: 766
    become: yes
    with_items: "{{ supervisor_config_files }}"
    when: (supervisor_config_files is not none) or (supervisor_config_files|length)
    #when: supervisor_config_files
    notify:
      - supervisor restart

  - name: Create log directory
    file: path="{{supervisor_log_dir}}" state=directory mode=0755
    become: yes

  - name: Create consumer executable scripts
    template: src={{ item.src }} dest={{item.dest}} mode=0744
    become: yes
    with_items:
      - { src: sample_supervisor_script.sh.j2, dest: /usr/local/bin/sample_supervisor_script.sh }
    notify: restart sample_supervisor_script