---
  - name: start docker
    systemd:
      name: docker
      enabled: true
      state: started

  - name: common | packages | update all
    package:
      name: "*"
      state: latest
    tags:
      - update
      - software
    when: ansible_os_family = 'RedHat'