---
  - name: Step 1 Download repo
    shell: >
      sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
    register: jenkins-Step1

  - name: Step 2 import jenkins key
    shell: >
      sudo rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
    register: jenkins-Step2

  - name: Step 3 Install jenkins
    yum:
      pkg: "{{ item }}"
      state: present
    with_items:
      - jenkins