---

#################### Ubuntu (Debian) Update apt-get ####################

  - name: Install packages.
    apt:
      pkg="{{ item }}"
      state=present
    with_items: "{{ apt_install }}"
    when: is_ubuntu and apt_install

  - name: Download Debian Packages
    become: yes
    get_url:
      url: "{{ item.url }}"
      dest: "/tmp/{{ item.deb }}"
      mode: 0644
    with_items: "{{ apt_debian_packages }}"
    when: is_ubuntu and apt_debian_packages

  - name: install Debian Packages Dependies
    become: yes
    shell: >
      apt-get install -f
    when: is_ubuntu

  - name: install deb packages manually
    action: shell dpkg-query -f '${Package}\n' -W {{item.name}} || dpkg -i /tmp/{{item.deb}}
    register: deb
    changed_when: deb.stdout != item.name
    with_items: "{{ apt_debian_packages }}"
    when: is_ubuntu and apt_debian_packages

#  - name: Installing NodeJS
#    become: yes
#    apt:
#      name: nodejs
#      state: installed
#    tags:
#      - nodejs-install
#
#  - name: Installing NodeJS legacy
#    become: yes
#    apt:
#      name: nodejs-legacy
#      state: installed
#    tags:
#      - nodejs-legacy-install
#
#  - name: Download phpstorm
#    get_url:
#      url: https://download.jetbrains.com/webide/PhpStorm-2016.3.2.tar.gz
#      dest: /tmp/phpstorm.tar.gz
#
#  - name: Unpack phpstorm
#    unarchive:
#      src: /tmp/phpstorm.tar.gz
#      dest: /opt/
#      owner: "{{ user }}"
#      creates: /opt/PhpStorm-163.10504.2
#    register: unpack
#
#  - name: Fix the PHPStorm permissions folder
#    file:
#      path: /opt/PhpStorm-163.10504.2
#      owner: "{{ user }}"
#      recurse: yes
#    when: unpack.changed
#
#  - name: Create phpstorm .desktop file
#    copy:
#      src: ../files/jetbrains-phpstorm.desktop
#      dest: /usr/share/applications/jetbrains-phpstorm.desktop
#      owner: root
#      group: root
#      mode: "u=rw,g=r,o=r"

####################  Fedora (RedHat) Update dnf  ######################

  - name: (RedHat) install packages
    become: true
    dnf: name="{{item}}" state=latest
    with_items:
      - "{{ yum_install }}"
    when: is_fedora and yum_install

  - name: (RedHat) Download rpm Packages
    get_url:
      url: "{{ item.url }}/{{ item.rpm }}"
      # url: ${baseUrl}/${rpm} 
      dest: /tmp
      mode: 0644
    with_items: "{{ redhat_rpm_packages }}"
    when: is_fedora

  - name: (RedHat) install rpm packages manually
    dnf: 
      name: /tmp/{{item.rpm}}
      state: present
    with_items: "{{ redhat_rpm_packages }}"
    when: is_fedora and redhat_rpm_packages

  - name: Check if package was installed
    command: rpm -q atom
    register: atom_installed
    changed_when: atom_installed.rc == 1
    ignore_errors: yes

  - name: Download atom package
    get_url: url=https://atom.io/download/rpm dest=/tmp/atom_x86_64.rpm
    when: atom_installed.rc == 1

  - name: Install the RPM
    dnf: name=/tmp/atom_x86_64.rpm
    when: atom_installed.rc == 1